#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap           10 

bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color "#6e6a86"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on

# Autostart
$HOME/.fehbg *
$HOME/.config/polybar/launch.sh
picom

